# Generated by Django 6.1.1 on 2026-10-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_request_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delivery_method',
            field=models.CharField(default='pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='mobile',
            field=models.CharField(default='', max_length=20),
        ),
    ]
